import { Controller } from "@hotwired/stimulus"

// Handles confirmation dialogs for button_to forms that shouldn't use Turbo Drive.
// With Turbo Drive disabled (drive = false), data-turbo-confirm is not intercepted,
// so this controller provides the same SweetAlert2 confirmation without needing Drive.
//
// Usage: add to the form generated by button_to:
//   form: { data: { controller: "confirm",
//                   action: "submit->confirm#confirm",
//                   confirm_message_value: "Are you sure?" } }
export default class extends Controller {
  static values = { message: String }

  async confirm(event) {
    if (!this.messageValue) return

    event.preventDefault()

    if (!window.Swal) {
      HTMLFormElement.prototype.submit.call(this.element)
      return
    }

    const swalWithBootstrap = window.Swal.mixin({ buttonsStyling: true })
    const result = await swalWithBootstrap.fire({
      icon: "warning",
      html: this.messageValue,
      title: "Are you sure?",
      showCancelButton: true,
      confirmButtonText: "Yes",
      cancelButtonText: "Cancel",
    })

    if (result.value) {
      // Use native submit to bypass Stimulus and Turbo event listeners.
      // The form still includes _method and authenticity_token hidden fields.
      HTMLFormElement.prototype.submit.call(this.element)
    }
  }
}
