import { Controller } from "@hotwired/stimulus"

// Handles the staffing sign-up button via AJAX rather than a full page navigation.
//
// Replaces the legacy app/assets/javascripts/admin/staffings.js script.
//
// Behaviour:
//   * The host element is the <form> generated by button_to. On submit, we
//     intercept and PUT the same path with a .json suffix.
//   * On a successful JSON response, we show a success toast (with a Google
//     Calendar add-link) and replace the form/button with the user's name.
//   * If the response carries an error or the request fails, we fall back to
//     a normal page reload so the server-rendered flash drives the UX.
//
// Usage:
//   <%= button_to "Sign Up", admin_staffing_sign_up_path(job),
//                 method: :put,
//                 form: { data: { controller: "staffing-signup",
//                                 action: "submit->staffing-signup#signUp",
//                                 staffing_signup_job_id_value: job.id } } %>
export default class extends Controller {
  static values = { jobId: Number, confirmMessage: String }

  async signUp(event) {
    event.preventDefault()

    if (this.confirmMessageValue) {
      const swalWithBootstrap = window.Swal.mixin({ buttonsStyling: true })
      const result = await swalWithBootstrap.fire({
        icon: "warning",
        html: this.confirmMessageValue,
        title: "Are you sure?",
        showCancelButton: true,
        confirmButtonText: "Yes",
        cancelButtonText: "Cancel",
      })
      if (!result.value) return
    }

    const form = this.element
    const button = form.querySelector("button, input[type=submit]")

    if (button) {
      button.disabled = true
      button.style.display = "none"
    }

    fetch(`/admin/staffings/job/${this.jobIdValue}/sign_up.json`, {
      method: "PUT",
      headers: {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "X-CSRF-Token": this.#csrfToken()
      },
      credentials: "same-origin"
    })
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`)
        return response.json()
      })
      .then((data) => this.#handleSuccess(data))
      .catch((error) => this.#handleError(error))
  }

  // Private

  #handleSuccess(data) {
    if (data.error) {
      // Server reported a logical error — fall back to a full reload so the
      // user sees the flash message from the HTML response.
      window.location.reload()
      return
    }

    const startTime = new Date(data.js_start_time * 1000)
    const endTime   = new Date(data.js_end_time * 1000)
    const startStr  = this.#formatForGoogleCalendar(startTime)
    const endStr    = this.#formatForGoogleCalendar(endTime)

    const calendarTitle = `${data.name} - ${data.staffable.show_title}`
    const googleCalendarUrl =
      "http://www.google.com/calendar/event?action=TEMPLATE" +
      `&text=${encodeURIComponent(calendarTitle)}` +
      `&dates=${startStr}/${endStr}` +
      "&location=Bedlam Theatre, Edinburgh" +
      "&trp=true" +
      "&sprop=website:http://www.bedlamtheatre.co.uk" +
      "&sprop=name:Bedlam Theatre"

    const startLocal = startTime.toLocaleString()
    const message =
      `<p>Thank you for choosing to staff ${data.staffable.show_title} as ${data.name} on ${startLocal}.</p>` +
      `<p><a href="${googleCalendarUrl}" target="_blank" rel="noopener">Add to Google Calendar</a></p>`

    if (typeof window.showToast === "function") {
      window.showToast("success", message)
    }

    // Replace the entire button_to form with the user's name. We look up
    // every form on the page that targets this same job so that any clones
    // (e.g. inside a confirmation modal) are updated together.
    const userName = `${data.user.first_name} ${data.user.last_name}`
    const span = document.createElement("span")
    span.textContent = userName

    const allForms = document.querySelectorAll(
      `[data-controller~="staffing-signup"][data-staffing-signup-job-id-value="${this.jobIdValue}"]`
    )

    if (allForms.length > 0) {
      allForms.forEach((el, index) => {
        if (index === 0) {
          el.replaceWith(span)
        } else {
          el.replaceWith(span.cloneNode(true))
        }
      })
    } else {
      this.element.replaceWith(span)
    }
  }

  #handleError(error) {
    // eslint-disable-next-line no-console
    console.error("Staffing signup error:", error)
    window.location.reload()
  }

  #formatForGoogleCalendar(date) {
    const pad = (n) => String(n).padStart(2, "0")
    const year    = date.getUTCFullYear()
    const month   = pad(date.getUTCMonth() + 1)
    const day     = pad(date.getUTCDate())
    const hours   = pad(date.getUTCHours())
    const minutes = pad(date.getUTCMinutes())
    const seconds = pad(date.getUTCSeconds())
    return `${year}${month}${day}T${hours}${minutes}${seconds}Z`
  }

  #csrfToken() {
    const meta = document.querySelector('meta[name="csrf-token"]')
    return meta ? meta.getAttribute("content") : ""
  }
}
