# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Project-specific exclusions
AllCops:
  Exclude:
    - lib/generators/**/templates/**/*
    - db/schema.rb
    - db/queue_schema.rb
    - db/cache_schema.rb
