test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

wasabi:
  service: S3
  bucket: bedlam-theatre-website
  endpoint: https://s3.eu-central-1.wasabisys.com
  region: eu-central-1
  access_key_id: <%= Rails.application.credentials.dig(:wasabi, Rails.env.to_sym, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:wasabi, Rails.env.to_sym, :secret_access_key) %>

wasabi_mirrored:
  service: Mirror
  primary: wasabi
  mirrors:
    - local
